/********************************************************************************
** Programa.: IQueryCondition.cls
** Data.....: 16/03/2020
** Objetivo.: Interface de condicoes de execucao
********************************************************************************/

interface classes.query.IQueryCondition:

    method public char conditionStatement(input condition as int).
    method public char select().

end interface.
